env:
  global:
  - CC_TEST_REPORTER_ID=13ad85e8b00e6655fc096fca8f991b69d9fcb1dabd86167471fcae6b9eb6832f

sudo: required

language: node_js

addons:
  chrome: stable

node_js:
- '8.9'

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"

after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

jobs:
  include:
  - stage: Test
    script: npm run lint && npm run test -- --code-coverage
  - stage: Production build
    script: npm run build:prod
    if: branch = master AND type != pull_request
  - stage: S3 Deploy
    script: echo "Deploying to S3"
    if: branch = master AND type != pull_request
    deploy:
      provider: s3
      access_key_id: AKIAWXGBVQDYE7TBBB7O
      secret_access_key:
        secure: m+MEuLZ709G1YYwZS+PhL42/FGAgnCDqk9fWjedwKHsbRtlB+4ACMITnh+fu+Hs1cArFgNpAPuVd5SeRU+hbjtCRZdmJZGkpxFNXosnlwpfPL7ByraLUtZnUZGFKhSrvZA+LBL0H1PjAnI4go5LUy/pIWs3a7PPb8J5iJw2/dkc6eSnmMBa0lqu1vhawgFP+sQnrQ5F2Gw82H4fHe4vntZQIODNmreylaU8N7/j+dsz/0eGSVB8bgjaqEFAHRLK77vFwRg+NVvr7/Mf9WH5j+sBTsSVs/V/9Sl3f3VIijW86GWNg+oOG8BhyNbfg8+sqKHyofBKhLlr7+qO7c5cvWIwiUpfk73N/zmZXCACBZ+vlvxAPUYEappgjQ7XeH+81Wj3NjT0UijPN6t2igS8xMXYm+v5doR+VHJwMdY7D1FkUfByHO1+X+GrvLjIYRzKjcFCuMy1TvX8fEvZJl4Hr+RXIYuNlWfYkrYW//X70aX11CPchiGNADI+50LnKup325+xbuFaCKslccJGqSsrSxPoB+2yiVIt/1pLNmLVQjs7J97JK2QjXCf9jqT0kwYXRdIIPUOdOffebxCWZaqBWA3RJ1+qSfw6f+hnj9jrqws88BTmKEjXwSDvpFP61/2xBcNG4opoT9X9RtG7mhRSUb04vnbWhF3ZPCljcmRYyjPw=
      bucket: iamthechad.com
      local-dir: dist
      upload-dir: datacalc-ng
      acl: public_read
      on:
        repo: iamthechad/datacalc-ng
        branch: master

notifications:
  slack:
    secure: JDagsb2MGcm9LReT4vZGsuGyf7EkbK4y6m3PKrrr+wqzJUG+5AZ9CGDTn7dGhoyOHGSFonNiaUceSIwVXz8z8/RaIpnRs/bvoUg2fwbdyO0EnK8oeFjQ6ma4O+iJN3iuEHsRUigbCE+9vWIiD3RNznSUjiLVDLB4jgZFBvEbP3zoqQ1xra3HCuBlBywfLPEoQhiFmD1zSbYiOm1Y/P2Ady3Pl9tYtSY/fjeTuY+Y75thjjNNA0bIMh4fdZNTvee3QliM51QD7Dz522a2UvXHF3mBgKBtIhhfflFBJPr8Gcbx73Osi7p5JymOFRP3RMh4tA6a2xzPMHCbtUrNApxJ7kRvAM/4NEvaysIoU+QdEVw48RqgNej4eYOI15vty4fcEt1aEdS2FvfCG8JoHCXF7U4Dhr/zjT3abREbN47ex9m24LbOjBMRZkzsh+YI7VVcW3q1NiqnhDEPHAyjNGrn2gnzeXLKMovQqbwRpYeNOw4f5MNHYNvhxlCMK+kCqFOzVCfJm4UHJyHkss1wqykuSGG+05g+eu9cKmIAskPvq9stiQKWyQMFuvV3AASwVx3UH9LlmOcQWuf/5VeV049H/bLjUVber51pKO+pIvhgNjfBNrZs80fI+kkW5PoD6zJ7QjqWGplJjdtNP2bbDOfQnyYotuCjbdhydsPnn3TJSqw=
